### ISSUE TITLE
docker 的mysql 8.0 root找不回密码，重置也失败，导致无法远程连接。

### ISSUE THREAD

**Issue by eluotao** [rocboss/paopao-ce#95]

**Comment by eluotao** [comment]
还是失败连接数据库，导致无法手动修改手机号基本信息，想局域网搭建使用。

![Mysql授权](https://i.imgur.com/aLd1GSe.png)
![连接数据库]( https://i.imgur.com/GxsGa8E.png)

**Comment by alimy** [comment]
1. 你这个是不是端口号错了， 确定是导出在3306吗；
2. 你要是已经赋权了，就可以不用绑定到127.0.0.1这个地址了否则外网连不上：
```yaml
version: '3.1'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: paopao
      MYSQL_USER: paopao
      MYSQL_PASSWORD: paopao
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ./scripts/paopao-mysql.sql:/docker-entrypoint-initdb.d/paopao.sql
      - ./data/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - paopao-network

  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - 6379:6379
    networks:
      - paopao-network
  
  minio:
    image: bitnami/minio:latest
    restart: always
    environment:
      MINIO_ROOT_USER: minio-root-user
      MINIO_ROOT_PASSWORD: minio-root-password
      MINIO_DEFAULT_BUCKETS: paopao:public
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data/minio/data:/data
    networks:
      - paopao-network
  
  zinc:
    image: public.ecr.aws/prabhat/zinc:latest
    user: root
    restart: always
    ports:
      - 4080:4080
    volumes:
      - ./data/zinc/data:/data
    environment:
      ZINC_FIRST_ADMIN_USER: admin
      ZINC_FIRST_ADMIN_PASSWORD: admin
      DATA_PATH: /data
    networks:
      - paopao-network

  backend:
    build:
      context: .
    restart: always
    depends_on:
      - db
      - redis
      - zinc
      - minio
    # modify below to reflect your custom configure
    volumes:
      - ./config.yaml.sample:/app/paopao-ce/config.yaml
      - ./data/paopao-ce/data:/app/paopao-ce/data
    ports:
      - 8008:8008
    networks:
      - paopao-network

networks:
  paopao-network:
      driver: bridge

```

```sh
> docker compose ps 
```
可以看到绑定到那个端口号；

3. 另外你要修改什么手机信息？ 是不是需要绑定手机号码吗？
找到config.yaml或config.yaml.sample中的Features：
```yaml
Features:
  Default: ["Base", "MySQL", "Option", "MinIO", "LoggerFile"]
  Develop: ["Base", "MySQL", "Option", "Sms", "AliOSS", "LoggerZinc"]
  Slim: ["Base", "Sqlite3", "LocalOSS", "LoggerFile"]
  Base: ["Zinc", "Redis", "Alipay",]
  Option: ["SimpleCacheIndex"]
  Sms: "SmsJuhe"
```
在Default中去掉Sms ，绑定手机时任意验证码都可以绑定手机。

**Comment by alimy** [comment]
其实最简单的部署方式是使用sqlite3+LocalOSS部署:
```sh
%> git clone git@gihub.com:rocboss/paopao-ce.git
%> cd paopao-ce
%> mkdir data
%> sqlite3 data/paopao-ce.db
sqlite> .read scripts/paopao-sqlite3.sql
sqlite> .exit
```

修改config.yaml
```yaml
Features:
  Default: ["Base", "Option",  "Sqlite3",  "LocalOSS", "LoggerFile"]
  Base: ["Zinc", "Redis", "Alipay",]
  Option: ["SimpleCacheIndex"]
...
LocalOSS: # 本地文件OSS存储配置
  SavePath: data/oss
  Secure: True
  Bucket: paopao
  Domain: <你本机的IP地址>
....
Sqlite3: # Sqlite3数据库
  Path: data/paopao-ce.db
```

然后构建paopao-ce:
```sh
%> cd web && echo 'VITE_HOST=""'>.env && yarn && yarn build && cd -
%> make run TAGS='embed' 
# or
%> make build TAGS='embed'
%> release/paopao-ce
```

这样就可以构建一套可用的paopao-ce
